<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GG6P3L9" name="step_definition.Stepdef_login" tests="7" failures="0" timestamp="5 Dec 2020 14:00:43 GMT" time="23.884" errors="1">
  <testcase name="login_should_be_Unsuccessful" time="0.004" classname="step_definition.Stepdef_login"/>
  <testcase name="user_enters_all_valid_data" time="2.427" classname="step_definition.Stepdef_login"/>
  <testcase name="login_should_be_successful" time="0.003" classname="step_definition.Stepdef_login"/>
  <testcase name="user_is_on_login_page2" time="8.900" classname="step_definition.Stepdef_login"/>
  <testcase name="user_is_on_login_page" time="10.102" classname="step_definition.Stepdef_login"/>
  <testcase name="i_enter_Email_as_and_Password_as" time="0.000" classname="step_definition.Stepdef_login">
    <error type="org.testng.TestNGException" message="
Method i_enter_Email_as_and_Password_as requires 2 parameters but 0 were supplied in the @Test annotation.">
      <![CDATA[org.testng.TestNGException: 
Method i_enter_Email_as_and_Password_as requires 2 parameters but 0 were supplied in the @Test annotation.
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:202)
	at org.testng.internal.Parameters.createParameters(Parameters.java:138)
	at org.testng.internal.Parameters.createParameters(Parameters.java:387)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:462)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1303)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1019)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1108)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- i_enter_Email_as_and_Password_as -->
  <testcase name="click_on_Log_in" time="2.448" classname="step_definition.Stepdef_login"/>
</testsuite> <!-- step_definition.Stepdef_login -->
